// One-off generator: reads db/seed.sql (old 2-table layout) and emits a new
// seed file matching the 3-table customer_order / rfs_order / task schema.
//
//   node scripts/gen-seed.mjs > db/seed.sql.new
//
// Then diff and replace.  Deterministic: same input -> same output.
//
// Mapping rules:
//   - one wm_customer_order per old wm_order (uuid = co-001000N, fresh IDs)
//   - two wm_rfs_order per CO:
//       * LMA          sys_id rfs-002000N            number RFS002000N
//       * Connectivity sys_id rfs-002000(N+25)       number RFS002000(N+25)
//   - 17 tasks per CO; ONT task -> Connectivity RFS, the other 16 -> LMA RFS.
//     Tasks get fresh sys_ids wot-003000NNN to keep them clearly distinct
//     from the legacy wot-005xxxx series.
//   - phone numbers: Borken landline pattern "+49 2861 9XX-XXX", deterministic.
//   - order_date: earliest sys_updated_on of the WO's tasks, minus 14 days.
//   - scheduled_appointment: set on 3 specific COs to demo both button states.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const SRC = readFileSync(resolve("db/seed.sql"), "utf8");

// --- parse old wm_order rows ----------------------------------------------
const orderBlock = SRC.match(/INSERT INTO wm_order VALUES([\s\S]*?);/)[1];
const orderRegex = /\('([^']+)','([^']+)',(\d+),'([^']*)','([^']*)','([^']*)','([^']*)',(\d+),'([^']*)'\)/g;
const orders = [];
let m;
while ((m = orderRegex.exec(orderBlock)) !== null) {
  orders.push({
    old_sys_id: m[1],
    old_number: m[2],
    status_code: Number(m[3]),
    construction_status: m[4],
    customer_name: m[5],
    city: m[6],
    address: m[7],
    unit_count: Number(m[8]),
    set_name: m[9],
  });
}
if (orders.length !== 25) throw new Error(`expected 25 orders, got ${orders.length}`);

// --- parse old wm_task rows -----------------------------------------------
const taskRegex = /\('([^']+)','([^']+)','([^']+)','([^']+)','([^']+)','([^']+)','([^']*)','([^']+)'\)/g;
const tasks = [];
let tm;
while ((tm = taskRegex.exec(SRC)) !== null) {
  // Only match rows that look like task rows (sys_id starts with wot-)
  if (!tm[1].startsWith("wot-")) continue;
  tasks.push({
    old_sys_id: tm[1],
    old_number: tm[2],
    old_work_order: tm[3],
    short_description: tm[4],
    short_code: tm[5],
    state: tm[6],
    assignment_group: tm[7],
    sys_updated_on: tm[8],
  });
}
if (tasks.length !== 425) throw new Error(`expected 425 tasks, got ${tasks.length}`);

// --- deterministic CO number pool (Crockford base32, no I L O U) ----------
// Hand-picked to be visually distinct + pronounceable in pairs.
const CO_NUMBERS = [
  "7T4K-NM9P", "Q2H5-3FXR", "BWZ8-K1JD", "RT63-PVH7", "5SXM-9NGT",
  "ZF2D-J8KH", "MQ7T-V4P6", "K9BS-N3RW", "8XGH-CMD2", "VP5N-7JBQ",
  "T3FH-DK4M", "9GMS-NB7P", "QRH8-2VKZ", "B6DN-S4FT", "3KJM-XPN9",
  "HFGS-T7QB", "PNT4-MK9D", "Z2JB-5RXH", "47KP-FBDM", "MXNT-6QSH",
  "S5HD-N3PV", "B8MR-JK4G", "T6PQ-SXHN", "94KD-V7BM", "F3RJ-PQNH",
];
if (CO_NUMBERS.length !== 25) throw new Error("CO number pool size");

// --- which COs have an appointment scheduled ------------------------------
// Pick indices in 0..24.  Mix of statuses so the button shows both states.
const SCHEDULED_AT = new Map([
  [3,  "2026-05-18T09:00:00Z"],   // status 103 in progress
  [9,  "2026-05-21T13:30:00Z"],   // status 101 Open
  [15, "2026-05-23T10:00:00Z"],   // status 101 Open
]);

// --- helpers ---------------------------------------------------------------
const pad = (n, w) => String(n).padStart(w, "0");
const minusDays = (iso, d) => {
  const t = new Date(iso);
  t.setUTCDate(t.getUTCDate() - d);
  return t.toISOString().slice(0, 10);
};
const sqlStr = (s) => (s === null || s === undefined) ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;

// --- emit -----------------------------------------------------------------
const out = [];
out.push("-- Generated by scripts/gen-seed.mjs.  Do not edit by hand;");
out.push("-- regenerate via:  node scripts/gen-seed.mjs > db/seed.sql");
out.push("-- 25 customer orders × 2 RFS orders × 17 tasks/CO = 50 RFS + 425 tasks");
out.push("");

// Customer orders
out.push("INSERT INTO wm_customer_order VALUES");
const coRows = orders.map((o, i) => {
  const idx = i + 1;
  const uuid = `co-${pad(10000 + idx, 7)}`;
  const number = `CO-26-${CO_NUMBERS[i]}`;
  // earliest task date for this WO
  const myTasks = tasks.filter(t => t.old_work_order === o.old_sys_id);
  const earliest = myTasks.reduce((acc, t) => t.sys_updated_on < acc ? t.sys_updated_on : acc, myTasks[0].sys_updated_on);
  const order_date = minusDays(earliest, 14);
  // phone: +49 2861 9XX-XXX, deterministic from index
  const phone = `+49 2861 9${pad((idx * 37) % 100, 2)}-${pad((idx * 113) % 1000, 3)}`;
  const sched = SCHEDULED_AT.get(i) ?? null;
  return `  (${[
    sqlStr(uuid),
    sqlStr(number),
    sqlStr(order_date),
    sqlStr(o.customer_name),
    sqlStr(o.address),
    sqlStr(o.city),
    sqlStr(phone),
    sqlStr(sched),
    o.status_code,
    sqlStr(o.construction_status),
    o.unit_count,
    sqlStr(o.set_name),
  ].join(",")})`;
});
out.push(coRows.join(",\n") + ";");
out.push("");

// RFS orders (50 = 25 LMA + 25 Connectivity)
out.push("INSERT INTO wm_rfs_order VALUES");
const rfsRows = [];
const lmaIdByOldWo = new Map();
const connIdByOldWo = new Map();
orders.forEach((o, i) => {
  const idx = i + 1;
  const coUuid = `co-${pad(10000 + idx, 7)}`;
  const lmaSysId  = `rfs-${pad(20000 + idx, 7)}`;
  const connSysId = `rfs-${pad(20000 + 25 + idx, 7)}`;
  const lmaNumber  = `RFS${pad(20000 + idx, 7)}`;
  const connNumber = `RFS${pad(20000 + 25 + idx, 7)}`;
  lmaIdByOldWo.set(o.old_sys_id, lmaSysId);
  connIdByOldWo.set(o.old_sys_id, connSysId);
  rfsRows.push(`  (${[sqlStr(lmaSysId),  sqlStr(lmaNumber),  sqlStr(coUuid), sqlStr("LMA")].join(",")})`);
  rfsRows.push(`  (${[sqlStr(connSysId), sqlStr(connNumber), sqlStr(coUuid), sqlStr("Connectivity")].join(",")})`);
});
out.push(rfsRows.join(",\n") + ";");
out.push("");

// Tasks — fresh sys_ids in wot-003xxxx range, sequential.
out.push("INSERT INTO wm_task VALUES");
const taskRows = tasks.map((t, i) => {
  const idx = i + 1;
  const sysId  = `wot-${pad(30000 + idx, 7)}`;
  const number = `WOT${pad(30000 + idx, 7)}`;
  const isOnt = t.short_description === "ONT";
  const rfsType = isOnt ? "Connectivity" : "LMA";
  const rfsSysId = isOnt
    ? connIdByOldWo.get(t.old_work_order)
    : lmaIdByOldWo.get(t.old_work_order);
  return `  (${[
    sqlStr(sysId),
    sqlStr(number),
    sqlStr(rfsSysId),
    sqlStr(rfsType),
    sqlStr(t.short_description),
    sqlStr(t.short_code),
    sqlStr(t.state),
    sqlStr(t.assignment_group),
    sqlStr(t.sys_updated_on),
  ].join(",")})`;
});
out.push(taskRows.join(",\n") + ";");
out.push("");

process.stdout.write(out.join("\n"));
